services:
  backend:
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - USER_NAME=elias
      - USER_ID=1000
      - GROUP_NAME=elias
      - GROUP_ID=1000
      - ENV=dev
    volumes:
      - ./api:/api
      - ./data:/data
    expose:
      - 8000
    #ports:
    #  - "8000:8000"  # Commenté car géré par Nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.priority=2"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
    networks:
      - app-network
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    command: sh -c 'yarn install && yarn dev --host'
    environment:
      - USER_NAME=elias
      - USER_ID=1000
      - GROUP_NAME=elias
      - GROUP_ID=1000
    volumes:
      - ./app:/app
    expose:
      - 5173
    #ports:
    #  - "5173:5173"  # Commenté car géré par Nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    networks:
      - app-network

  traefik:
    image: "traefik:v2.11"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"

  database:
    image: postgres:latest
    command: ["postgres"]
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: lycee
      POSTGRES_DB: lycee
    volumes:
      - type: volume
        source: database-volume
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database-volume:
    driver: local