services:
  backend:
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - USER_NAME=elias
      - USER_ID=1000
      - GROUP_NAME=elias
      - GROUP_ID=1000
      - ENV=dev
    volumes:
      - ./api:/api
      - ./data:/data
    ports:
      - 8000:8000
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    command: sh -c 'yarn install && yarn dev --host'
    environment:
      - USER_NAME=elias
      - USER_ID=1000
      - GROUP_NAME=elias
      - GROUP_ID=1000
    volumes:
      - ./app:/app
    ports:
      - 5173:5173


  database:
    image: postgres:latest
    command: ["postgres"]
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: lycee
      POSTGRES_DB: lycee
    volumes:
      - database-volume:/var/lib/postgresql/data
    # Optionnel: exposer le port pour accès externe (à désactiver en production)
    # ports:
    #   - "5432:5432"


volumes:
  database-volume:
    driver: local
